name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron:  '3 * * * *'

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

      defaults:
        run:
        shell: bash

    steps:
    - name: Generate Token
      id: generate-token
      uses: actions/create-github-app-token@v1
      with:
        app_id: 856597
        private_key: ${{ secrets.BRANCH_PROTECTIONS_APP_PRIVATE_KEY }}
        owner: DbUp
      
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN  }}

    - name: Terraform Init
      working-directory: BranchProtections
      run: terraform init

    - name: Terraform Apply
      working-directory: BranchProtections
      run: terraform apply -auto-approve -input=false
      env:
        GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
