name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron:  '3 * * * *'
    
permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_token: ${{ secrets.BRANCH_PROTECTIONS_APP_TOKEN }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
